### ISSUE TITLE
darknet for yolov7

### ISSUE THREAD

**Issue by Miuney** [AlexeyAB/darknet#8611] opened 2022-07-26 04:11 UTC
hello,are there plans to update darknet for "yolov7"?

**Comment by dragan07-07** [comment] 2022-07-26 08:06
I am interesting in this question too. I need tiny-yolov7 pre-training model.

**Comment by Miuney** [comment] 2022-07-26 08:12
> I am interesting in this question too. I need tiny-yolov7 pre-training model.

https://github.com/AlexeyAB/darknet/issues/8595#issue-1296709732

**Comment by Miuney** [comment] 2022-07-26 08:13
> > I am interesting in this question too. I need tiny-yolov7 pre-training model.
> 
> [#8595 (comment)](https://github.com/AlexeyAB/darknet/issues/8595#issue-1296709732)

https://github.com/AlexeyAB/darknet/issues/8595#issuecomment-1179780967

**Comment by Miuney** [comment] 2022-07-26 08:14
> 

i think, it will help you.

**Comment by dragan07-07** [comment] 2022-07-26 08:16
Tnx. This is for I am looking for.

**Comment by bariscankurtkaya** [comment] 2022-07-30 00:39
@Miuney I think the problem is solved. So, could you please close the issue?

**Closed** 2022-08-09 03:05 UTC
