### ISSUE TITLE
Learning rate under multiple gpus

### ISSUE THREAD

**Issue by Pattorio** [AlexeyAB/darknet#1165] opened 2018-07-10 02:36 UTC
Hi AlexeyAB,

I find that if I set learning_rate=0.001 in .cfg file and use multiple gpus, say 4 gpus, to train, the learning rate in log would be 0.004, which equals to the number of gpus times the lr setting in the cfg file. Here are my questions:

1. I went through the code, but didn't find any thing about why lr in log would be num_gpus * lr. Could you please help me figure it out? 

2. Under this situation (using 4 gpus), what is the actual lr for each gpu, 0.001 or 0.004? Is it different from using 1 gpu and seting lr=0.001?

3. If the actual lr for each gpu is 0.004, does it mean that I have to consider the number of gpus when I set lr?

4. If I want to add new learning rate policy, what should I do? I have tried to do following things: 
a) add `new_policy` into` get_policy()` in `parcer.c`. 
b) add `if(net->policy == new_policy)` and corresponding operations in `parse_net_options()` in `parser.c`. 
c) add `case new_policy` in `get_current_rate()` in `network.c` 
d) add `new_policy` into learning_rate_policy struct in `darknet.h`
After doing these, lr in log file is just the one I set in .cfg file. It has no relation to number of gpus. Anything else to add/modify?

Look forward to hearing from you. Thanks!

**Comment by Pattorio** [comment] 2018-07-11 11:49
Thank you for your quick response, Alexey!

It takes me some time to understand your word that

> Joseph done increase 4x learning_rate and decrease /4 loaded_images when are used 4 GPU

I read the code and log, here is my understanding:
First, Joseph increase 4x learning_rate when using 4 GPU which is obviously according to:
https://github.com/pjreddie/darknet/blob/f6d861736038da22c9eb0739dca84003c5a5e275/examples/detector.c#L27

Then, for each iteration, network will train `batch_in_cfg` images. And every 4 iterations, it will do "Sync", which skips `4 * (ngpus - 1) * batch_in_cfg` images ( just add such number of images into net->seen without training):
https://github.com/pjreddie/darknet/blob/d3828827e70b293a3045a1eb80bfb4026095b87b/src/network.c#L1078

Therefore, he decreases /4 loaded_images when using multiple (>1) GPUs. Am I right?

Do you have any idea about variable `interval` in his code above? It's really confusing setting learning_rate=ngpus * learning_rate

Besides, I have some other questions:
1. You said in https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> Increase network-resolution by set in your .cfg-file (height=608 and width=608) or (height=832 and width=832) or (any value multiple of 32) - this increases the precision and makes it possible to detect small objects. if error Out of memory occurs then in .cfg-file you should increase subdivisions=16, 32 or 64

When we do 'test', usually we set batch=1 and subdivisions=1. Why is setting subdivisions=16,32 or 64 useful? If batch=1, subdivisions=16, net->batch=1/16 is not an integer. Why it works?

2. Once I forgot to change value of batch and subdivisions in cfg file when testing, but the objects in image were still detected. After changing batch=1 and subdivisions=1, I tested again and found that I got much better result which had less missing/wrong boxes. Why? How does these two variables works when testing?

3.  When training, I get log as follow.
![image](https://user-images.githubusercontent.com/22585548/42569172-3812e050-8542-11e8-9eda-344441e5e398.png)
I thought it should look like this:
```
Region 16 ..
Region 23 ..
Region 16 ..
Region 23 ..
```
One region 16, one region 23, this kind of pattern, on and on.
But as showing above in the blue box, the second should be region 23, however it is missing. Why? Where is it? When the region would be ignored (not be shown in the log)?

So many questions, lol. If you can answer any of them, I would appreciate!

**Comment by AlexeyAB** [comment] 2018-07-11 15:59
1. In my repo,  batch= and subdivisions will be taken from cfg-file only fro Training. In other cases it will be set batch=1 subdivisions=1 automatically: https://github.com/AlexeyAB/darknet/blob/3d2d0a7c98dbc8923d9ff705b81ff4f7940ea6ff/src/detector.c#L1091

2. I don't know why is it happen. In my repo it should be the same. Can you show screenshots of this differ?

3. Do you use multi-GPU. So training goes simultaneosly, so it can go in different order due to parallel execution.

**Comment by sharoseali** [comment] 2018-08-07 06:40
Hi .. Please answer this...  AlexeyAB,  i trained aeroplane data set on the model same as you defined in your Repo. There were 3094 images in the data set ... The error rate is not decreasing after 2200th iterations.. .. when i test the model, it wasn't good.. enough.. (detecting..... but not so accurate)  
Now please let me know.. what i do know so that my model give good results.. if i increase learning rate ..and continue training from 2200th iteration, can i got better results......please let me know any one of you...... please..?

**Comment by Pattorio** [comment] 2018-08-07 07:50
@sharoseali Hey, I have to say there are many reasons causing bad detection results. Data set itself, learning rate, number of iterations, input image size, etc. are the things you should consider. It's not easy to tell you what you should do based on your description.

> The error rate is not decreasing after 2200th iterations

For my experience, keep training may help. But you must be careful of overfitting.

**Comment by AlexeyAB** [comment] 2018-08-07 10:47
@sharoseali Just train about 6000 - 10 000 iterations
Alse read:
https://github.com/AlexeyAB/darknet#when-should-i-stop-training
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

**Comment by AlexeyAB** [comment] 2018-08-07 14:45
@sharoseali 

>  after make changing in cfg file: will i petform training from start

Yes, you should start training from the begining.

**Comment by Pattorio** [comment] 2018-08-08 06:38
@sharoseali 
What do you mean "in horizontal dimension"? Any example?

> the box draw around the detected aerplane is very wide

You can check your anchor in cfg file. You had better generate anchors for your own data set.
you can use calc_anchor in this repo:
https://github.com/AlexeyAB/darknet#how-to-improve-object-detection

> if there are more than one plane in a test image .. it also draw wronge bounding boxes

I think it depends on your training set. If the images in your training set have single object, say one plane in one image, you may get result like this. You can add image that has more than one planes into your training set.

>  how can i find that my model is overfitted..??

Alexey has replied you, answer is here:
https://github.com/AlexeyAB/darknet#when-should-i-stop-training

**Comment by Pattorio** [comment] 2018-08-08 07:33
@AlexeyAB 

Let's continue previous discussion.

Training under multiple gpus looks like this way:

If max_batch = 16, batch = 2.

For 1 gpu, it loads 2 images in one iteration. After 4 iterations, it will load `4*2 = 8` images. It will take 16 iterations to finish training (load 32 images in total).

For 4 gpus, they load `batch*ngpus = 2*4=8` images in one iteration. Each gpu will get 2 images to train. After 4 iterations, they will load `4*8 = 32` images. 

Oops, now they have finish what 1 gpu should do under this setting - loading 32 images. So they just wait (Actually they don't need to wait. They just skip next 3 iterations) and say "we finished" till the 4th iteration (using "Sync").

Therefore, under the same setting, 1-gpu-mode and 4-gpus-mode load the same number of images. 

For 4 gpus: each gpu will load x1/4 images compare to the gpu in 1-gpu-mode. And for each iteration, 4 gpus load x4 images to train, which can be considered that 4-gpu-mode has x4 batch size.
According to this: https://miguel-data-sc.github.io/2017-11-05-first/

> For the ones unaware, general rule is “bigger batch size bigger learning rate”

So the learning rate *= ngpus.

Is this explain reasonable?

Any I did experiment, ylabel is loss. The yellow line is training result under 4-gpu-mode with cfg_lr. The pink line is result under 4-gpu-mode with lr*=ngpus. Ignore the others.

x4 lr have better result.

![image](https://user-images.githubusercontent.com/22585548/43822667-5b228a30-9b1f-11e8-92c6-a8e962b90ecc.png)

**Comment by AlexeyAB** [comment] 2018-08-08 11:34
@Pattorio 

If `max_batch = 16, batch = 2` then

* For **1 GPU**: will be loaded **32 images in total**, and `learning_rate = lr_cfg`

* For **4 GPUs**: will be loaded **8 images in total**, and `learning_rate = 4*lr_cfg`

More: https://github.com/AlexeyAB/darknet/issues/1098


So may be according to this rule “bigger batch size bigger learning rate” - it uses 4x higher learning_rate, and to compensate it - it loads 4x times less images

> According to this: https://miguel-data-sc.github.io/2017-11-05-first/
> 
> > For the ones unaware, general rule is “bigger batch size bigger learning rate”

**Comment by sharoseali** [comment] 2018-08-08 19:44
**@AlexeyAB **
sir... u have suggested me to read the content **How to improve object detection:**..The problem is that i am using yolo v2 and the changes sugested here is related to YOLO v3 .. how can i made changing in   yolo v2 cfg file i-e yolo-obj.cfg to detect small objects....

How can i managed these instructions: 
 

- training for small objects - set layers = -1, 11 instead of .........
(when i change this the training didnt start and ends up giving message **no error**)
to detect small objects and and increase precision... u suggest
- and set stride=4 instead of ..........
(In yolo v3 this change is under **[un sample]** layer) which is not in yolo-obj.cfg

- recalculate anchors for your dataset for width and height from cfg-file: darknet.exe detector calc_anchors data/obj.data -num_of_clusters 9 -width 416 -height 416 then set the same 9 anchors in each of 3 [yolo]-layers in your cfg-file
(if i increase resolution by 608 x 608 than whether i use width 416 -height 416 or width 608-height 608 in upper point)

please explain so that i start my training asap

**Comment by sharoseali** [comment] 2018-08-08 19:56
**@AlexeyAB ** 
Sir one thing more to ask is that... I have to show confusion matrix (map between my training and testing values during the training process) which shows whether the model is over or under fitted..
How can i draw it....?  Thanks

**Comment by Pattorio** [comment] 2018-08-09 12:11
@AlexeyAB 

4 gpus only 8 images in totoal? Why?

Log file shows that 4 gpus will load 4 times images than 1 gpu. And code in detector.c also shows that total number of images is ngpus times than 1 gpus.

`int imgs = net.batch * net.subdivisions * ngpus;`

**Comment by AlexeyAB** [comment] 2018-08-09 12:29
@Pattorio 

For 4 GPUs the iterations will be increased by 16 instead of 4:
`*nets[0].seen += interval * n * nets[0].batch * nets[0].subdivisions = 4 * 4 * batch_from_cfg`

* https://github.com/AlexeyAB/darknet/blob/24c889d85705643ca4860dea88827a7f1893b731/src/network_kernels.cu#L363

* https://github.com/AlexeyAB/darknet/blob/24c889d85705643ca4860dea88827a7f1893b731/src/network_kernels.cu#L149

**Comment by AlexeyAB** [comment] 2018-08-09 12:53
@sharoseali 

Calculation anchors for yolo v2:

`darknet.exe detector calc_anchors data/obj.data -num_of_clusters 5 -width 13 -height 13`

----

For `yolov2-voc.cfg` for detection small objects:

* `layers=-15` https://github.com/AlexeyAB/darknet/blob/d59a172a1d6eed66ecba6493199767f955edc7a0/cfg/yolov2-voc.cfg#L209

* set `stride=4` 
 https://github.com/AlexeyAB/darknet/blob/d59a172a1d6eed66ecba6493199767f955edc7a0/cfg/yolov2-voc.cfg#L220

But yolov3 much more better for detection small objects.

**Comment by Pattorio** [comment] 2018-08-13 03:10
@AlexeyAB 

> If max_batch = 16, batch = 2.

> For 1 gpu, it loads 2 images in one iteration. After 4 iterations, it will load 4*2 = 8 images. It will take 16 iterations to finish training (load 32 images in total).

> For 4 gpus, they load batch*ngpus = 2*4=8 images in one iteration. Each gpu will get 2 images to train. After 4 iterations, they will load 4*8 = 32 images.

1. Am I right ?

2.  I know that for 4 GPUs the iterations will be increased by 16 instead of 4 by using
`*nets[0].seen += interval * n * nets[0].batch * nets[0].subdivisions = 4 * 4 * batch_from_cfg`. Am I right if I explain it in this way:

>  After 4 iterations, 4 gpus have finished what 1 gpu should do under this setting - loading 32 images. So they just wait (Actually they don't need to wait. They just skip next 12 iterations by using `*nets[0].seen += interval * (ngpus-1) * nets[0].batch * nets[0].subdivisions = 4 * (4-1) * batch_from_cfg`) and say "we finished" till the 16th iteration.

If in both 1 and 2 I am right, even though 4 gpus increase iteration by 16, they load 4x image than 1 gpu in one iteration. Therefore, 1-gpu-mode and 4-gpus-mode should load the same number of images.

For 1 gpu:
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 finish (32 images in total)
For 4 gpus:
8 8 8 8 0 0 0 0 0 0 0 0 0 0 0 0 finish (32 images in total) 
"0" means `*nets[0].seen += interval * (ngpus-1) * nets[0].batch * nets[0].subdivisions = 4 * (4-1) * batch_from_cfg`)

**Comment by AlexeyAB** [comment] 2018-08-13 12:33
@Pattorio 

If `batch=2`

> For 4 gpus, they load batchngpus = 24=8 images in one iteration. Each gpu will get 2 images to train. After 4 iterations, they will load 4*8 = 32 images.

No.

* For 4 gpus it loads 8 images (batch x gpus)  in one iteration:  https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/detector.c#L73

* these 8 images will be divided by 4 gpus - 2 images for each 1 gpu: 
    *  https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/network_kernels.cu#L386-L389
    * https://github.com/AlexeyAB/darknet/blob/a9fef1bd66e6b2c40c344c1bdcd33bb1d209461c/src/data.c#L1267-L1278

**Comment by AlexeyAB** [comment] 2018-08-20 20:48
@Pattorio 

> 1xGPU
> ![image](https://user-images.githubusercontent.com/22585548/44333216-c57fa680-a4a0-11e8-8082-964398590d0d.png)
> 
> 4xGPU
> ![image](https://user-images.githubusercontent.com/22585548/44333196-b698f400-a4a0-11e8-82d6-5e84f629e237.png)

These images show that was loaded the same number of images `6144`. But actually for 1 GPU was loaded `6144` images, and for 4xGPU was loaded `1536` images.

> I think your word For 4 GPUs the iterations will be increased by 16 instead of 4 is the same as my word 4-gpu-mode will skip next 12 iterations.

Yes.


4xGPU trains 4x faster, but iteration counter increases 16x faster.


> For 1 gpu:
> 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 finish (32 images in total)
> For 4 gpus:
> 8 8 8 8 0 0 0 0 0 0 0 0 0 0 0 0 finish (32 images in total)

If `mini_batch=2` then for 4xGPU the each GPU can't process 8 images in one iteration, because there isn't enough GPU-RAM for it. Exactly to avoid CUDA out of memory we use `mini_batch=batch/subdivisions`. And if we found that maximum mini_batch=2, then 2 will be used for both 1xGPU and 4xGPU.

**Comment by Pattorio** [comment] 2018-08-21 07:05
@AlexeyAB 

I think I figure out what you're talking about!

In your repo, in multiple GPUs case, you use function `train_networks()`. But actually you didn't define this function in `network.c `. Only function refer to training network is `train_network()`.

https://github.com/AlexeyAB/darknet/blob/e1801f5aec1373475682fa4d0850a3469dab6ef7/src/detector.c#L184-L191

`train_network()` in your repo is the way that Joseph used for training in 1 GPU. Although there are some subtle difference between your codes, I think the your purposes are the same. It defines the `mini_batch=batch/subdivisions` and use` mini_batch` for training - network will split batch into several mini_batch and run `subdivisions` times to finish one iteration. Since you use `train_network()` instead of `train_networks()`, in multiple GPU case, each gpu will only `mini_batch` images. Therefore, images loaded by 4XGPU will be less than 1 GPU.

https://github.com/AlexeyAB/darknet/blob/e1801f5aec1373475682fa4d0850a3469dab6ef7/src/network.c#L312-L330

In Joseph's repo, he defined the function `train_networks()`. No more `mini_batch`. Each gpu will get `batch` images to train. For one iteration, 4XGPU will load 4 times images than 1 GPU. And after 4 iterations, it has a "Synchronize" mechanism which is what I said about "skipping 12 iterations".

https://github.com/pjreddie/darknet/blob/98e2a7674fd6a81349735db6f5b34229c871113a/src/network.c#L1091-L1121

The way Joseph used in `train_networks()` is what I talked all above and explained lol. I hope I don't have any misunderstanding about your codes.

**Comment by Pattorio** [comment] 2018-08-21 07:10
Since you use `mini_batch` in multiple GPU case, each iteration multiple GPU will load less images than 1 GPU, corresponding learning should be 1/ngpu according to “bigger batch size bigger learning rate”. That's might the reason for #1456

**Comment by Pattorio** [comment] 2018-09-14 11:33
Hey Alexey, thank you for your patience and response. 

I am still a little confused. I am afraid I have some misunderstanding of the code.

> These images show that was loaded the same number of images 6144. But actually for 1 GPU was loaded 6144 images, and for 4xGPU was loaded 1536 images.

If it is true, it means with the same max_batches in cfg file, 4-GPUs will load 4 times images less than 1-GPU. I don’t think it makes sense. 

I understand the use of mini_batch. In both 1-GPU-model and 4-GPU-model, network will load mini_batch=batch/subdivisions images for one forward.

https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/src/network.c#L314-L328
https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/src/network.c#L289-L298

In total, each GPU will do forward_network subdivisions times and then update the network.
For 4 GPUs, after each of them updates the network, they have to sync_nets

https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/src/network.c#L1072-L1089

In this way, in one iteration, each GPU loads batch images and uses mini_batch images to do forward_network for subdivisions times. 4 GPUs will load 4*batch images in total.
Therefore, for 1 GPU was loaded 6144 images, and for 4xGPU was loaded the same number of images.

Do I have any misunderstanding of the code?

**Comment by AlexeyAB** [comment] 2018-09-14 11:51
@Pattorio 
> In total, **each GPU will do forward_network subdivisions times** and then update the network.
> For 4 GPUs, after each of them updates the network, they have to sync_nets
> 
> https://github.com/pjreddie/darknet/blob/680d3bde1924c8ee2d1c1dea54d3e56a05ca9a26/src/network.c#L1072-L1089
> 
> In this way, **in one iteration, each GPU loads batch images** and uses mini_batch images to do forward_network for subdivisions times. **4 GPUs will load 4*batch images in total.**

Yes. This is correct for 1 iteration. But isn't correct for 1000 iterations.

Make a little experiment. Change the source code so that the iterations are increased by 100 instead of 1. Then all that you said is true. But in total will be loaded 100x times less images.

**4xGPU increases iterations by +16 instead of +4.** - This is the main thing.
Training log for 4xGPU is incorrect.

**Comment by Pattorio** [comment] 2018-09-14 11:58
@AlexeyAB 

I did some experiments to find the best parameters when training with multiple GPUs.

I choose a small training set. It is about 90 images with 1 class.

 For 1 GPU, I set parameter in cfg file in this way. 
![image](https://user-images.githubusercontent.com/22585548/45548087-9f59e600-b855-11e8-8300-fb6d27b9cad6.png)
And get the result:
![image](https://user-images.githubusercontent.com/22585548/45548097-ac76d500-b855-11e8-9781-718f166b2dbf.png)

Then, in the following experiments I use 4 GPUs.

**DEFAULT-LR**
First, I change nothing in cfg file and use 4 GPUs to train. 
![image](https://user-images.githubusercontent.com/22585548/45548133-cdd7c100-b855-11e8-825e-9e1c48ac6700.png)
However, it can detect nothing.
![image](https://user-images.githubusercontent.com/22585548/45548146-dd570a00-b855-11e8-99ad-006f38508876.png)

**4x-LESS-LR**
According to your recommendation in issue #1456 , I first decrease `learning_rate` by 4 times and keep `max_batches` unchanged.
![image](https://user-images.githubusercontent.com/22585548/45548245-34f57580-b856-11e8-8133-886d409d63ac.png)
After 2000 iterations, it can detector something which seems good.
![image](https://user-images.githubusercontent.com/22585548/45548255-3d4db080-b856-11e8-9bba-d8412835592d.png)

**4x-LESS-LR-4X-MORE-ITERATIONS**
Then I increase both `burn_in` and `max_batches` by 4 times and decrease `learning_rate` by 4 times as you said in #1456 .
![image](https://user-images.githubusercontent.com/22585548/45548294-59e9e880-b856-11e8-846b-a665df8c26ed.png)
Get even better result than 1-GPU.
![image](https://user-images.githubusercontent.com/22585548/45548308-6c642200-b856-11e8-9213-86a02eb54254.png)

**4x-MORE-ITERATIONS**
I think it might be useful to keep `learning_rate` unchanged and just train more iterations. So, I increase both `burn_in` and `max_batches` by 4 times.
![image](https://user-images.githubusercontent.com/22585548/45548382-b51bdb00-b856-11e8-9647-b3fc8c32bcc1.png)
However, it didn't converge.
![image](https://user-images.githubusercontent.com/22585548/45548430-e3011f80-b856-11e8-9001-9109e2837ce4.png)
![image](https://user-images.githubusercontent.com/22585548/45548432-e5637980-b856-11e8-91b7-ef83c391af50.png)

It seems that keeping `learning_rate` unchanged in multiple gpu training is not a good choice.

**4x-LESS-LR-4x-MORE-ITERATION-DEFAULT-BURN_IN**
Finally, I just want to figure out the whether parameter `burn_in` will help in training. I decrease the `learning_rate` and increase the `max_batches`, but keep `burn_in` unchanged.
![image](https://user-images.githubusercontent.com/22585548/45548683-cdd8c080-b857-11e8-9af3-948b30e78cb3.png)
Not so good.
![image](https://user-images.githubusercontent.com/22585548/45548687-d3360b00-b857-11e8-86b4-5effc0010de7.png)


Conclusion for my experiments: for training with multiple GPUs, it might get good result by increasing both `burn_in` and `max_batches` by `ngpus` times and decrease `learning_rate` by `ngpus` times.

Above experiments are for reference. You can add some tips about training with multiple GPUs in Readme.

**Comment by Pattorio** [comment] 2018-09-14 12:12
> 4xGPU increases iterations by +16 instead of +4. - This is the main thing.

Oh! I think I got it. If it is increase by +4, 4-GPU-model and 1-GPU-model will load the same number of image, right?

**Comment by AlexeyAB** [comment] 2018-09-14 12:17
> Oh! I think I got it. If it is increase by +4, 4-GPU-model and 1-GPU-model will load the same number of image, right?

Yes.

----

> Conclusion for my experiments: for training with multiple GPUs, it might get good result by increasing both burn_in and max_batches by ngpus times and decrease learning_rate by ngpus times.
> 
> Above experiments are for reference. You can add some tips about training with multiple GPUs in Readme.

Yes, there is already about 4 time less learning rate.
I will add about 4x times more burn_in= and max_batches=.

> Adjust the learning rate (cfg/yolov3-voc.cfg) to fit the amount of GPUs. The learning rate should be equal to 0.001, regardless of how many GPUs are used for training. So learning_rate * GPUs = 0.001. For 4 GPUs adjust the value to learning_rate = 0.00025.

**Comment by Pattorio** [comment] 2018-09-15 05:34
That's great!

Thank you soooooo much! You are so patient!

**Closed** 2018-09-15 05:36 UTC

**Comment by AlexeyAB** [comment] 2018-12-09 21:38
@Eniac-Xie Hi,

> Beside, when we set batch=64 and subdivisions=16, then every GPU only takes 4 images for forward, am I right?

No. In this case each GPU use mini-batch = 4 images - for forward-backward. And batch=64 images - for weights updating.
And 4 different weights arrays (for each GPU) will be synchronized for each iteration: https://github.com/AlexeyAB/darknet/blob/7bd6b2f7201baa6777d1f50652beb36578374e86/src/network_kernels.cu#L414

But may be yes, in this case we should use learning_rate 4x according to this article: https://arxiv.org/abs/1706.02677v2

**Comment by AlexeyAB** [comment] 2018-12-09 22:38
@Pattorio Hi,

I changed this in Readme as recommendation for small datasets: https://github.com/AlexeyAB/darknet#how-to-train-with-multi-gpu

**Comment by aidevmin** [comment] 2023-08-15 07:02
@Pattorio 
Thanks for deep investigation.
As you mentioned above 
```
Conclusion for my experiments: for training with multiple GPUs, it might get good result by increasing both burn_in and max_batches by ngpus times and decrease learning_rate by ngpus times.
```
As my understanding, `batch`, `subdivisions` are not changed, `max_batches = #GPUs * max_batches (for 1 GPU)`, `lr = lr(for 1 GPU) / #GPUs`, `burn_in = #GPUs * burn_in (for 1 GPU)`. Is that correct?

Can you confirm that with the above config, training time of 4 GPUs case is smaller than training time of 1 GPU?
