### ISSUE TITLE
Yolov2 Compiling and Training: Problems on Windows 10

### ISSUE THREAD

**Issue by Razkolnikova** [AlexeyAB/darknet#7699] opened 2021-05-10 16:23 UTC
I have been having issues setting up Darknet. I will be using yolov2 to detect cerebral microbleeds for a neuroscience project. After battling Darknet for a few days, I managed to install it and successfully download the train, test and validation Pascal VOC data by using the below general configuration/set up:

- Cmake-GUI 3.2 (binary distributions, not source)
- MSVS 2019
- CUDA 11.1
- cuDNN 8.0.5
- OpenCV 4.2.0

I always get an error when running **darknet.exe detector train data/voc.data yolo-voc.2.0.cfg darknet19_448.conv.23** in cmd: 
*'darknet.exe' is not recognized as an internal or external command,
operable program or batch file.*

I cannot seem to understand the reason why.

In addition, when following the pjreddie instructions to modify cfg for Pascal Data:

""""
classes= 20
train  = <path-to-voc>/train.txt
valid  = <path-to-voc>2007_test.txt
names = data/voc.names
backup = backup
""""

I change the Notepad file and all / to the backslash, does that make a difference? 

Can you please shed some light as to how to successfully train the data?

Many thanks in advance!

**Comment by Razkolnikova** [comment] 2021-05-12 20:42
Windows 10 users who have succeeded with the installation, would any of you mind sharing which versions of the programs you have used?

**Comment by cenit** [comment] 2021-05-30 21:33
@Razkolnikova is this issue still valid after the help you had on discord?
if the problem is fixed, please close this issue

**Comment by Razkolnikova** [comment] 2021-05-31 06:20
Issue closed now, thank you @cenit!

**Closed** 2021-05-31 06:19 UTC
