### ISSUE TITLE
broken windows installation

### ISSUE THREAD

**Issue by zanaviska** [AlexeyAB/darknet#7273] opened 2021-01-22 08:27 UTC
After [this](https://github.com/AlexeyAB/darknet/commit/00d578e327c22638ea12e73c4efb74c798c08de5#diff-3258bc4162690adead72c70b672093e68c92e86a4628148f0015d61738f21b5a) commit, [this](https://github.com/AlexeyAB/darknet#how-to-compile-on-windows-using-vcpkg) way to install darknet on Windows 10 crash with following error
![image](https://user-images.githubusercontent.com/31745527/105465875-2af0a680-5c9c-11eb-9171-7ac84d21a2fb.png)

I suppose it's becouse of "improving windows build", that require ninja build system, but this shoud be mentioned in your readme

**Comment by ROBYER1** [comment] 2021-01-22 23:44
Just trying out manually adding Ninja but unsure what todo since this change

**Comment by cenit** [comment] 2021-01-23 08:05
sorry bad default.
I already pushed PR #7279, let me check if CI validates it and then it should be fixed

**Comment by ROBYER1** [comment] 2021-01-23 11:02
> sorry bad default.
> I already pushed PR #7279, let me check if CI validates it and then it should be fixed

After adding Ninja manually last night to my path, I got it to install after 4 attempts running through the vcpkg install. I'm not too keen to remove darknet and install again after that headache as it's always been a massive pain to install on windows especially as I have a 30 series GPU so I needed OpenCV4.5 which was absent from vcpkg for months 🤯

However, as I saw you also pushed a commit for ensurong OpenCV4.5 is installed by default - I will verify soon if Vcpkg installed OpenCV 4.5 by default with Cuda and Cudnn support else I will rip out my install and do it all again

**Comment by cenit** [comment] 2021-01-23 15:34
yes I just finished work on vcpkg and now there is OpenCV 4.5 there :)

**Comment by ROBYER1** [comment] 2021-01-23 15:48
![image](https://user-images.githubusercontent.com/10745594/105606592-4938ce00-5d92-11eb-93a7-79d8a90a7c6a.png)
Yep we're good :) I built it with ninja before your new push, will that affect anything on Windows version since you removed Ninja default after?

**Comment by cenit** [comment] 2021-01-23 16:00
nope. Ninja is better, but it's just an option and as such it should not be the default. Of course, if you have it, you should prefer it :)

**Comment by ROBYER1** [comment] 2021-01-23 16:01
> nope. Ninja is better, but it's just an option and as such it should not be the default. Of course, if you have it, you should prefer it :)

Thanks :) the install with Ninja seemed blazing fast when it worked. Thanks so much for fixing Vcpkg install too hope it helps loads of people who struggle with the Windows install every damn time like I do🤣

**Comment by anandakevin** [comment] 2021-01-31 14:54
> nope. Ninja is better, but it's just an option and as such it should not be the default. Of course, if you have it, you should prefer it :)

Thanks cenit :), anyway, just want to confirm, is the opencv 4.5 has already been pushed to the vcpkg online library? I only found 4.3 just now when trying to find opencv package in vcpkg

![image](https://user-images.githubusercontent.com/41095065/106387930-b42b7a00-640e-11eb-8ded-0136870bd3ea.png)

Pretty unsure whether this is caused by some local cache or perhaps others? 🤣

**Comment by cenit** [comment] 2021-01-31 22:03
You need to do a git pull in the vcpkg folder to download updated references.
But looking at the name you might have downloaded a tarball and not cloned the repo.
Please download vcpkg with this command:

`git clone https://github.com/Microsoft/vcpkg`

**Closed** 2021-04-15 23:05 UTC
